name: uts_linkaja
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+2

  cupertino_icons: ^1.0.8

  image_picker: ^1.1.2

  flutter_svg: ^2.0.15
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
